### ISSUE TITLE
Text block not displaying all data

### ISSUE THREAD

**Issue by lemusi** [BALKANGraph/OrgChartJS#14]
Hi, 
First off... I want to say that this is a great plugin! It's been working great and it has many features. So, thank you for keeping it updated and so useful!! Kudos!!

Now, this is more a request than an issue:  Is there a way to customize the text block that pops up when you click on any node? I would love to be able to:
- Show fields on the nodes but hide them on the text block. Or viceversa (How does the script knows which fields to show on the nodes? maybe I haven't figured that out)
- To be able to see all the text when you scroll down (I have many fields, so right now the last items get cut off and I don't see them)
- To change the CSS of the text.  I would love it if it is more compact and the user doesn't have to scroll down too much.

Anyway, let me know if you have any ideas on how I can accomplish those things.  Let me know in case you are interested in seeing my implementation of your plugin, so I can give you access to my system.

Best regards,

Ivan

**Comment by BALKANGraph** [comment]
I'm glad to here that you like the library 

In order to see the edit view on node click set odeMouseClickBehaviour to BALKANGraph.action.edit

Here is an example: https://jsfiddle.net/BALKANGraph/d8bnpfse/?utm_source=website&utm_medium=embed&utm_campaign=d8bnpfse

- All fields that are not empty for selected node are shown in the edit view. There is not way to specify which fields to show in the current version. In one of the next versions we are planning to implement new option something like: 
`editFields: ["name", "email", "phone", etc.]`
- We have released new version 3.8.1 where the issue with not visible nodes is fixed
- You can use Custom Edit Form - https://balkangraph.com/OrgChartJS/Docs/Edit

I'm very interested on your implementation please send a link to support@balkangraph.com for review

**Comment by plamen-peshev** [comment]
Get the latest version

See "Change the Edit fields in the default Edit form" section from [this ](https://balkangraph.com/OrgChartJS/Docs/Edit) help article
