### ISSUE TITLE
Number column in group

### ISSUE THREAD

**Issue by perezcoder** [BALKANGraph/OrgChartJS#236]
Can i set the number of columns in a group? I would set the number of columns to 2. 
Thank you very much for the support

**Comment by plamen-peshev** [comment]
The current version does not support it

I have added your request for future consideration

**Comment by plamen-peshev** [comment]
Implemented in version 6.0.6

if you are using group_grey template set columns=1 and the group will have only one column

OrgChart.templates.group_grey.columns = 1;

https://balkangraph.com/OrgChartJS/Demos/Grouping

**Comment by annie-l** [comment]
Hi @plamen-peshev -- I noticed that this doesn't seem to work (at least as I expected) when you have a horizontal chart (e.g. orientation: OrgChart.orientation.left_top):

`OrgChart.templates.group_grey.columns = 1`
![image](https://user-images.githubusercontent.com/530852/72852971-10d55000-3c65-11ea-81d1-a9dab93fad96.png)

In this case, you should set the number of columns to the number of nodes in the group:
`OrgChart.templates.group_grey.columns = 5`
![image](https://user-images.githubusercontent.com/530852/72853043-26e31080-3c65-11ea-93f2-d32e7aa3f746.png)


Maybe you could update https://balkangraph.com/OrgChartJS/Docs/Grouping to note how to do it for horizontal layouts?

**Comment by plamen-peshev** [comment]
Can you try to set it to unknown
`
OrgChart.templates.group_grey.columns = unknown;`

**Comment by annie-l** [comment]
Hi, using just `unknown` (or `"unknown"`) causes a reference error:

![image](https://user-images.githubusercontent.com/530852/72928570-14bcad00-3d0d-11ea-8f10-c71d786aad61.png)


using `OrgChart.unknown` does not cause an error but gives 2 columns for 5 nodes:

![image](https://user-images.githubusercontent.com/530852/72928528-ff478300-3d0c-11ea-93f0-677be8033955.png)

Since I know the number of nodes I'm adding to the group, it's fine for my use case to use that number as the number of columns.

**Comment by ZornitsaSerbezova** [comment]
annie-l, thank you for the suggestion.
We will consider it for implementing in future releases.

**Comment by ZornitsaSerbezova** [comment]
Now we have complete new implementation of [groups.](https://balkangraph.com/OrgChartJS/Demos/Grouping). I'll close this issue. Feel free to reopen it if needed.
