### ISSUE TITLE
Performance issue when sticky is set to false

### ISSUE THREAD

**Issue by nbpro** [BALKANGraph/OrgChartJS#409]
We are facing performance issue when we are setting  **sticky: false**
With this configuration, the maps doesn't bounce back to boundary and with every mouseleavehandler  the map/graph is drawn from cache, in our case the graph hangs on redraws as we drag the map/graph and doesn't load after some time.

If we remove set sticky to default, its working fine. We really need this  for smooth drag of map.Please find attached image for reference. This is also shared over balkan graph support mail.
![Performance_issue_when_sticky_is_set_to_false__-_nkumar_gainsight_com_-_Gainsight_Mail](https://user-images.githubusercontent.com/3526202/87271879-2760b380-c4f2-11ea-83fe-8a177737e6ba.png)

**Comment by ZornitsaSerbezova** [comment]
Hi Neeraj,

On 7/1/2020 2:29 PM I have answered to your email about the same issue, and asked you to reproduce the error in the file that i have send you. In order to investigate the issue, we need to reproduce it, but we couldn't. You have something specific in your code that is causing the issue. 


Regards,
Zornitsa

**Comment by ZornitsaSerbezova** [comment]
Hi nbpro,
I'll close this issue. Please answer to our email if you still have this issue.
