### ISSUE TITLE
Expand

### ISSUE THREAD

**Issue by 170107173** [BALKANGraph/OrgChartJS#476]
Hi, I'm new in Balkan OrgChart, so i can't solve problem with expanding. After pressing button "+"(expand), position of a view is changing. How to stay still at the position?

**Comment by ZornitsaSerbezova** [comment]
Here in these screenshots the expanding node is not moving:
![image](https://user-images.githubusercontent.com/19305472/96423697-5fb71280-1202-11eb-9f04-83ec4bbc4d52.png)

![image](https://user-images.githubusercontent.com/19305472/96423660-4f9f3300-1202-11eb-8672-624e7aca1d6a.png)

Could you show us what position exactly do you mean and what do you expect?

**Comment by beloofficial** [comment]
Imagine that Jack Hill has a thousand of children in depth, if you click on the plus(expand), your position will go down to the end, to the bottom. But I would like me to stay on the Jack Hill card. 
In my case, there are about 10,000 cards, and when I press plus(expand), I am thrown down to the lowest child, and I get lost because of this
![96423660-4f9f3300-1202-11eb-8672-624e7aca1d6a](https://user-images.githubusercontent.com/43059691/96757428-37dcd000-13f7-11eb-8ed2-89365b38abe0.png)

**Comment by ZornitsaSerbezova** [comment]
For a workaround we have a demo that is centering the expanded node:  https://balkangraph.com/OrgChartJS-Demos/Center

**Comment by beloofficial** [comment]
Wow, thanks a lot.
