### ISSUE TITLE
When publish online not showing 

### ISSUE THREAD

**Issue by smss123** [BALKANGraph/OrgChartJS#598]
when i in localhost everything is work fine but when i publish the project to server 
now showing  come with this error 

Access to XMLHttpRequest at 'https://ind-balkangraph.azurewebsites.net/api/OrgChartJS' from origin 'https://tree.developkw.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
orgchart.js:1 Error: <svg> attribute viewBox: Expected number, "NaN,NaN,1197,913".
(anonymous) @ orgchart.js:1
(anonymous) @ orgchart.js:1
(anonymous) @ orgchart.js:1
(anonymous) @ orgchart.js:1
n.onerror @ orgchart.js:1
error (async)
OrgChart._ajax @ orgchart.js:1
(anonymous) @ orgchart.js:1
OrgChart.remote._findRegion @ orgchart.js:1
OrgChart.remote._setPositions @ orgchart.js:1
OrgChart.server._read @ orgchart.js:1
(anonymous) @ orgchart.js:1
OrgChart.state._get @ orgchart.js:1
OrgChart.server.read @ orgchart.js:1
OrgChart._draw @ orgchart.js:1
OrgChart @ orgchart.js:1
window.onload @ (index):319
load (async)
(anonymous) @ (index):77
orgchart.js:1 POST https://ind-balkangraph.azurewebsites.net/api/OrgChartJS net::ERR_FAILED

i use ASPNET MVC 4

**Comment by ZornitsaPesheva** [comment]
Could you please isolate the issue in jsfiddle?

**Comment by nlonguit** [comment]
I am too having this issue with CORS policy
"Access to XMLHttpRequest at 'https://easia-balkangraph.azurewebsites.net/api/OrgChartJS' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."
Google Chrome is now blocking the Balkangraph site also since the certification is not proved to be safe
![image](https://user-images.githubusercontent.com/11536790/135745292-640cc1e9-80ea-4deb-b4ee-dbf5bff38404.png)

**Comment by ZornitsaPesheva** [comment]
We have fixed the SSL issue.
