### ISSUE TITLE
The content of the nodes is hidden when moving, increasing and decreasing zoom

### ISSUE THREAD

**Issue by doarsal** [BALKANGraph/OrgChartJS#61]
The content of the nodes is hidden when moving, zooming and zooming. In my example I have 500 nodes.

https://imgur.com/FYHVYIc

**Comment by BALKANGraph** [comment]
It is expected behavior for performance optimization

Browsers cannot handle tons of html dom element, for that reason before the animation OrgChart JS hides some of the elements

You can tune that by changing the following constants:
 - BALKANGraph.TEXT_THRESHOLD = 150;
 - BALKANGraph.IMAGES_THRESHOLD = 70;
 - BALKANGraph.LINKS_THRESHOLD = 150;
 - BALKANGraph.EXPCOLL_THRESHOLD = 40;
 - BALKANGraph.ANIM_THRESHOLD = 50;


With the default consts OrgChart JS works well on computer with 2GB RAM
