### ISSUE TITLE
Wrong line with assistant child nodes

### ISSUE THREAD

**Issue by cavone-leonardo** [BALKANGraph/OrgChartJS#620]
**Use Case**
we have reproduced the issue in this [jsfiddle](https://jsfiddle.net/5f0kmv6s/):

**Description**
We have a chart with a root with two nodes of type 'assistant' an two other nodes.
The first node 'assistant' has two child nodes.
The chart is displayed as follows:

![image](https://user-images.githubusercontent.com/67264683/140543900-a9aa8537-8e1e-4f2d-a3b8-f3bb4040959d.png)

**Expected result**

![image](https://user-images.githubusercontent.com/67264683/140545144-ec59faa9-9bb3-4b3e-84f1-520ed9a24da3.png)

Thanks

**Comment by ZornitsaPesheva** [comment]
Pleaee read this issue:
https://github.com/BALKANGraph/OrgChartJS/issues/345

**Comment by ZornitsaPesheva** [comment]
Fix the line in the node:
        OrgChart.templates.invisibleGroup.node += '<line x1="0" y1="240" x2="**270**" y2="240" stroke-width="1" stroke="#aeaeae"></line>';

You can do it dinamically if needed.
You can have different templates for that hidden node and change them based on assistant children number

**Comment by cavone-leonardo** [comment]
Creating invisible nodes, with invisible groups and lines, in the case of our application, is not a solution.
We have clients who have very complex organizational structures, where nodes are dynamically added.
This means that we should do these operations (changes to the template) every time we want to add a child to an assistant node.
Is this the only workaround or are you planning an implementation of the above solution?

Thanks

**Comment by ZornitsaPesheva** [comment]
Hi Leonardo,

We have added this in our to do list and will contact you when it is implemented.

**Comment by gmaggiodev** [comment]
Any news, we are waiting for this feature. Our customers are pushing for having it asap.

**Comment by ZornitsaPesheva** [comment]
Hi Gianluca, 
We haven't still worked on this.

**Comment by corradofacchini** [comment]
Hi, it is very urgent to solve this issue, we cannot pubblish the chart in with thsi problem

**Comment by ZornitsaPesheva** [comment]
Sorry, but we can not implement this so urgent, as we have tasks with higher priority.

**Comment by corradofacchini** [comment]
Txs for your replay, but not this is very urgent for us.
We asked for it several months ago

Grazie,
Ciao Corrado

Da: ZornitsaPesheva ***@***.***>
Inviato: 21 January 2022 11:40
A: BALKANGraph/OrgChartJS ***@***.***>
Cc: FACCHINI Corrado ***@***.***>; Comment ***@***.***>
Oggetto: Re: [BALKANGraph/OrgChartJS] Wrong line with assistant child nodes (Issue #620)


Sorry, but we can not implement this so urgent, as we have tasks with higher priority.

—
Reply to this email directly, view it on GitHub<https://mibc-fr-06.mailinblack.com/securelink/?key=eyJ1cmwiOiJodHRwczovL2dpdGh1Yi5jb20vQkFMS0FOR3JhcGgvT3JnQ2hhcnRKUy9pc3N1ZXMvNjIwI2lzc3VlY29tbWVudC0xMDE4Mzg3NzEyIiwibGFuZyI6IkVOIiwidG9rZW4iOiJnQUFBQUFCaDZvMXNlWmhkMW41SG1hQjQ5REdtbnAyX1F6ZW9uOVpyaEhXc0J4ZURzQlp4aUg4QzJ6OXBTdWFvV3lUQzF0cVZTcHhGbk9PcjJ0ZUpjY0F2R2J1dzVTdmpPMUhKTS1TT0tKNGY1amhHQTcybDZ1aWdHd0ZoQ21Zc1g0cmg0b2pONE5adjAzYmVUVk0tY0dENU04NHI2T2V2UDdPa3ZZS245WGtCaGNuY04taDl0MER1MHgtRU1IWVJocXFKZWd0U2oyX0I1cl9UU1RSUm12dTN6TUZKMWliQzlTTUJWbXF0Vl9KQU1wRmdjTjBlelZNSGU5YjFTTmFEV3dPR3pNUklmUkdYU1NIY00yYzJOdTNiTjcwS3puSnFyYWxHa3ZDSlF6ZzhZRmlnUHk1VnlBNThFUnc3Y0tidzFlaWF6RnVIS3RLVyJ9>, or unsubscribe<https://mibc-fr-06.mailinblack.com/securelink/?key=eyJ1cmwiOiJodHRwczovL2dpdGh1Yi5jb20vbm90aWZpY2F0aW9ucy91bnN1YnNjcmliZS1hdXRoL0FWVFlMVklXWURWQlZLT1NEUFM0U1VEVVhFWldWQU5DTkZTTTVIT0hMSVJBIiwibGFuZyI6I%20kVOIiwidG9rZW4iOiJnQUFBQUFCaDZvMXNzNG9HVU4wVFpJTDdLdWhUMXlHdnJiWFNaMlZFMWRTTUdvUlZ6Z0tsZUJLYjI4QnBhbmpNNXNpYm9TZ2ZVaWVRZVk1TlVxSERUUnlWSFIyS05uSXJOTTVPM3FrLWU4SURiZnJfUmdSai1LNzQ0OUUwZ1lMY2k4UGN4bkU0aVpIZ0p4UW1PWURVLUFxSUFzZktIMDc3dnBEck5FVUw4a0R3dzE1NWwyd1pPUUo5SkIyYkhDdWVDOHQ4bVZQSW9peDVtdU5aOWVnNFp4aWRpemlHSFc3SVotalgzVXpadkJpVmh0bEtGR3BWMFJPcjUxR1g3U0JtdUxJbEhWYUdRdFJaVXpLZEh6bVQyMWp5YmYwSzVHN1BVNGt5VV9FUWNfRUxCaDcwZ0NoV2IxRTJJT3pPZkpPUllQbFhiUmlqVTFhWSJ9>.
Triage notifications on the go with GitHub Mobile for iOS<https://mibc-fr-06.mailinblack.com/securelink/?key=eyJ1cmwiOiJodHRwczovL2FwcHMuYXBwbGUuY29tL2FwcC9hcHBsZS1zdG9yZS9pZDE0NzczNzY5MDU/Y3Q9bm90aWZpY2F0aW9uLWVtYWlsJm10PTgmcHQ9NTI0Njc1IiwibGFuZyI6IkVOIiwidG9rZW4iOiJnQUFBQUFCaDZvMXNsUzFXNU5DWnBQSklrSmkyeG96dGhKYllfbnZzVV9kTTY2RERLUDd6SFV1bjVCMklfQzZ6YkVxY0s1a19VaHp2RFZjRC1ULVJ5ZDJrN0VpVFZGWEpMeGxQSENkaVB0RVU3MTJpWHVDQTZsQWZrS1ZRWVVpQzZKT0pLaHdqWk5MTk5Ea2dqY0NVdGJhTWRaOFY2ZUNZQ3ZaZWZDM21BYWVaSVVlREQ5R3%20VhWDVQTzhqUUo0cm11ZGZZdmFwdm1hdGtvaHlfZGFSaS1VVnhJd0ZScGh3ODM1WmRvQ0hCRGVZb2RCZ0VyMk9SWFI1U1NldkJJMHJ1RjBNc3VTeHRVZGlESHYxY0tkcXVwSmNTQ3RScndNdWpHZkxabGN0ak1sNF9WenRwbjdWQWZtQWd1SlVONGZaUlZ5QnE4RFFhNVlXSCJ9> or Android<https://mibc-fr-06.mailinblack.com/securelink/?key=eyJ1cmwiOiJodHRwczovL3BsYXkuZ29vZ2xlLmNvbS9zdG9yZS9hcHBzL2RldGFpbHM/aWQ9Y29tLmdpdGh1Yi5hbmRyb2lkJnJlZmVycmVyPXV0bV9jYW1wYWlnbiUzRG5vdGlmaWNhdGlvbi1lbWFpbCUyNnV0bV9tZWRpdW0lM0RlbWFpbCUyNnV0bV9zb3VyY2UlM0RnaXRodWIiLCJsYW5nIjoiRU4iLCJ0b2tlbiI6ImdBQUFBQUJoNm8xc1AwaFJXSmhIanFBcWNTXzR1ZGhfSGs3WVRhTG51ZUs4Z2U3Ml9KeGhLcnRjZnB0N2FuQTJ4YzlDdFVwNzdtbWpRc0VFYlQzbWp5Y1B3UjV0TU1sSzhFei1ldzBfakZueDZUZTJDaWNKMWd5QWMxTHlkOXNnUERmTHBVZnBUcmUxZ0ROSjNCWlptNkg2Yk9RbFg2dE9GZmxqQ0VRZUpRcUVJUEJXNDd6UGthZkV0NlBWNFFENTNtYlZodk1mbUVnTFgxYk1sRVlPdEFkcjQxbmFSR0VPb2FpOXY0RTRmbUdLN2JhcGpsX2liSW1WZVJhTno5VE1FbUVPaElzTHgtRkRHQkpjWWtwTUZ3TlpYcDlKV3BZdWpNRHNOdEVTQjRRal80c0g4SzJfaXlQSGVsMm5KSFJlcmliNzNyN1BmRkJvIn0=>.
You are rec eiving this because you commented.Message ID: ***@***.******@***.***>>

**Comment by ZornitsaPesheva** [comment]
Sorry, we will try to do it soon.

**Comment by plamen-peshev** [comment]
The issue has been addressed in the latest version 8.02.19

https://code.balkan.app/wrong-line-with-assistant-child-nodes#JS
