### ISSUE TITLE
Load nodes with requests level by level

### ISSUE THREAD

**Issue by RaoufEbrahimi** [BALKANGraph/OrgChartJS#727]
Hello BALKAN

We've bought the professional license of your app to implement a graph with about 200K nodes and we cannot load all the nodes of the graph at the beginning, so I need to load every level of graph by user's demand request. Consequently, I contacted to your support and they gave me a sample code(Link : https://code.balkan.app/org-chart-js/loading-on-demand#JS), that was helpful but didn't solve the problem, In order to do that, I've considered three ways :
First, I need to know how to tell nodes that they have a child and then the collapse button gets generated by itself automatically, without rendering buttons manually, therefore, I can call my API in this function : " chart.on('expcollclick', function (sender, collapsing, id, ids) {" to retrieve next level from Data Base.
Secondly, if the first approach is not possible, please tell me how can I get "collapse status" in this function : "chart.on('redraw', function (sender, args, collapsing) {});"
And finally, if all above approaches are not possible, I must write new custom scripts to get the job done.
If you know any other solution, I'll be so grateful if you share it with me.

Thank You

**Comment by ZornitsaPesheva** [comment]
The example that we send you is the best approach to retrieve the children.
You will need to have the “hasChild” data in the backend, as you are not retrieving all the data and don’t have this information otherwise.
In the nodes data, the child is the node that has the information for the parent. The parent doesn’t know if it has a child.
