### ISSUE TITLE
License

### ISSUE THREAD

**Issue by geraldo** [BALKANGraph/OrgChartJS#81]
What is the license for your code? Is it free to use for a noncommercial educational project?

**Comment by plamen-peshev** [comment]
There is free version that you can use to evaluate the product

Download from [here](https://balkangraph.com/OrgChartJS/Download)

The product is not free to use for a noncommercial educational project

**Comment by geraldo** [comment]
Thanks for your answer, unfortunately I'm not able to use your library for my project.

**Comment by dclar43** [comment]
This is something that should REALLY be made more clear.  
  
I was about to write this library off since I wasn't able to find licensing information but decided to do a little more digging. It took me a while to find the License section at the bottom of the [Getting Started portion of the docs](https://balkangraph.com/OrgChartJS/Docs/GettingStarted). Even this explanation is somewhat confusing

**Comment by samcov** [comment]
Sort of confusing and possibly bait and switch to call it free in any sense. 

You may operate your business any way you desire, but it's pretty bad to get people using something that appears to be free, then after they've wasted their time developing, tell them it not free.

**Please consider being more up front about the costs, like in the readme.**

**Comment by salehmosleh** [comment]
what about some contries like Iran, they can't pay money and have credit cards because of US sanctions?!

**Comment by plamen-peshev** [comment]
Do you have PayPal?

**Comment by salehmosleh** [comment]
@plamen-peshev ، no we can't have PayPal, just webmoney and bitcoin.
